import { ToastContainer } from 'react-toastify'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { LayoutHOC } from '@/shared/components'
import { cn } from '@/shared/utils'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Gen Fiber - Web',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body
        className={cn('bg-gray-50', inter.className)}
        suppressHydrationWarning
      >
        <LayoutHOC>{children}</LayoutHOC>
        <ToastContainer />
      </body>
    </html>
  )
}
